CC:=gcc
CCFLAGS:=-Wall -Wextra
BIN:=.

q1: q1/q1.c
	$(CC) $(CCFLAGS) q1/q1.c -o $(BIN)/fork1

q2: q2/q2.c
	$(CC) $(CCFLAGS) q2/q2.c -o $(BIN)/fork2

q3: q3/q3.c
	$(CC) $(CCFLAGS) q3/q3.c -o $(BIN)/fork3

q4: q4/q4.c
	$(CC) $(CCFLAGS) q4/q4.c -o $(BIN)/fork4

q5: q5/q5.c
	$(CC) $(CCFLAGS) q5/q5.c -o $(BIN)/myshell

q6: q6/q6.c
	$(CC) $(CCFLAGS) q6/q6.c -o $(BIN)/myshell